from os import path
import json
import time
from typing import List, Set, Dict
from llmtool.LLM_utils import *
from llmtool.LLM_tool import *
from memory.syntactic.function import *
from memory.syntactic.value import *
from memory.syntactic.api import *
BASE_PATH = Path(__file__).resolve().parent.parent.parent

class SliceBugValidatorInput(LLMToolInput):
    def __init__(self, root_function_id: int, 
                 relevant_functions: Dict[int, Function], 
                 global_variables: List[str],
                 function_caller_to_callee_map: Dict[int, Set[int]],
                 bug_report: str) -> None:
        """
        :param root_function_id: the root function id
        :param relevant_functions: the relevant functions appearing in the slices
        :param function_caller_to_callee_map: the mapping from caller functions to callee functions
        :param bug_report: the bug report generated by the slice bug detector
        """
        self.root_function_id = root_function_id
        self.relevant_functions = relevant_functions
        self.global_variables = global_variables
        self.function_caller_to_callee_map = function_caller_to_callee_map
        self.bug_report = bug_report
        self.tree_str = self.build_tree_str()
        return
    
    def build_tree_str(self) -> str:
        """
        :return: the string representation of the caller-callee tree that will be used in the prompt
        """
        lines = []
        def traverse(func_id, prefix, is_last, visited):
            if func_id in visited:
                # Stop recursion if a cycle is detected.
                lines.append(prefix + ("└── " if is_last else "├── ") + f"{self.relevant_functions[func_id].function_name} (cycle)")
                return
            visited.add(func_id)
            branch = "└── " if is_last else "├── "
            line = (prefix + branch + self.relevant_functions[func_id].function_name) if prefix else self.relevant_functions[func_id].function_name
            lines.append(line)
            children = self.function_caller_to_callee_map.get(func_id, [])
            for i, child_id in enumerate(children):
                child_is_last = (i == len(children) - 1)
                new_prefix = prefix + ("    " if is_last else "│   ")
                traverse(child_id, new_prefix, child_is_last, visited.copy())
        traverse(self.root_function_id, "", True, set())
        return "\n".join(lines)

    def __hash__(self) -> int:
        relevant_function_ids = sorted(self.relevant_functions.keys())
        if len(self.global_variables) > 0:
            global_str = str(self.global_variables)
        else:
            global_str = ""
        function_caller_to_callee_map_strs = []
        for caller_id, callee_ids in self.function_caller_to_callee_map.items():
            function_caller_to_callee_map_strs.append(f"{caller_id}, {sorted(list(callee_ids))}")
        function_caller_to_callee_map_str = str(sorted(function_caller_to_callee_map_strs))
        return hash((str(relevant_function_ids), global_str, function_caller_to_callee_map_str, self.bug_report))
        

class SliceBugValidatorOutput(LLMToolOutput):
    def __init__(self, is_buggy: bool, explanation_str: str) -> None:
        """
        :param is_buggy: whether the construct is buggy. The construct can be a specific expression
        :param explanation_str: the string explaining the proof of concept
        """
        self.is_buggy = is_buggy
        self.explanation_str = explanation_str
        return
    
    def __str__(self):
        return f"Is buggy: {self.is_buggy} \nExplanation: {self.explanation_str}"


class SliceBugValidator(LLMTool):
    def __init__(self, bug_type: str, model_name: str, temperature: float, language: str, max_query_num: int, logger: Logger) -> None:
        """
        :param bug_type: the type of bug to detect
        :param model_name: the model name
        :param temperature: the temperature
        :param language: the programming language
        :param max_query_num: the maximum number of queries if the model fails
        :param logger: the logger
        """
        super().__init__(model_name, temperature, language, max_query_num, logger)
        self.prompt_file = f"{BASE_PATH}/prompt/{language}/bugscan/slice_bug_validator.json"
        return

    def _get_prompt(self, input: SliceBugValidatorInput) -> str:
        """
        :param input: the input of slice inliner
        :return: the prompt string
        """
        with open(self.prompt_file, "r") as f:
            prompt_template_dict = json.load(f)

        prompt = prompt_template_dict["task"]
        prompt += "\n" + "\n".join(prompt_template_dict["analysis_rules"])
        prompt += "\n" + "".join(prompt_template_dict["meta_prompts"])
        prompt = prompt.replace("<ANSWER>", "\n".join(prompt_template_dict["answer_format"]))
        prompt = prompt.replace("<QUESTION>", "\n".join(prompt_template_dict["question_template"]))
        prompt = prompt.replace("<BUG_REPORT>", input.bug_report)

        functions = []
        for function_id, function in input.relevant_functions.items():
            function_str = function.lined_code
            functions.append(function_str)
        prompt = prompt.replace("<PROGRAM>", "\n".join(functions))

        # append call tree
        prompt = prompt.replace("<FUNCTION_NAME>", input.relevant_functions[input.root_function_id].function_name)
        prompt = prompt.replace("<FUNCTION_CALL_TREE>", input.tree_str)

        # append the global variables
        if len(input.global_variables) > 0:
            global_variable_prompt = prompt_template_dict["global_variable"]
            global_variable_prompt = global_variable_prompt.replace("<GLOBAL_VARIABLE>", "\n".join(input.global_variables))
            prompt += "\n" + global_variable_prompt
        
        return prompt

    def _parse_response(self, response: str, input: SliceBugValidatorInput) -> SliceBugValidatorOutput:
        """
        :param response: the string response from the model (expected in JSON format)
        :return: the output of bug validator
        """
        try:
            # Extract JSON block if enclosed in ```json ... ```
            json_match = re.search(r'```json(.*)```', response, re.DOTALL)
            if json_match:
                json_str = json_match.group(1).strip()
            else:
                # Fallback: try parse whole response as JSON
                json_str = response.strip()

            # Parse JSON
            data = json.loads(json_str)

            answer_str = data.get("Answer", "").strip()
            bug_report_str = data.get("BugReport", "").strip()

            # Construct output
            output = SliceBugValidatorOutput(answer_str == "Yes", bug_report_str)
            self.logger.print_log("Output of bug validator:\n", str(output))

        except Exception as e:
            self.logger.print_log(f"Failed to parse JSON response: {str(e)}")
            output = None

        return output