import streamlit as st
import sys
from pathlib import Path
import json
from datetime import datetime
import traceback
import pandas as pd
# Add the parent directory to the system path
sys.path.append(str(Path(__file__).resolve().parents[2]))

from ui.logger import Logger
from llmtool.prompt_synthesizer import *
from llmtool.prompt_optimizer import *
from llmtool.bugscan.slice_bug_detector import *

# Language dictionary
language_dict = {
    "Cpp": "cpp",
    "Python": "python",
    "Java": "java",
    "Go": "go"
}

# Base path for results
BASE_PATH = Path(__file__).resolve().parents[3]

logger = Logger(f"{BASE_PATH}/log/webUI/{time.strftime('%Y-%m-%d', time.localtime())}.log")

def optimize_page():
    st.title("Detection Prompt Optimization")
    st.markdown("""
    This page allows you to create, view, and manage feedback for existing detection prompts.
    You can optimize your detection prompts based on this feedback.
    """)
    
    # Create tabs for adding new feedback, viewing existing ones, and optimizing prompts
    tab1, tab2, tab3, tab4 = st.tabs(["Add New Feedback", "View Existing Feedback", "Optimize Detection Prompt", "Evaluate Detection Prompt"])
    
    with tab1:
        st.subheader("Add New Feedback for Detection Prompt")
        
        # Language Selection
        language = st.selectbox("Language", 
            options=["Cpp", "Python", "Java", "Go"],
            key="feedback_language")

        # Bug Type Input
        bug_type = st.text_input("Bug Type", 
                               help="Enter the type of bug (e.g., NPD, BOF, UAF, ML)")
        
        # Current Prompt
        st.subheader("Current Detection Prompt")
        current_prompt = st.text_area("Paste the current detection prompt", 
                                     height=200,
                                     help="Paste the JSON prompt that needs optimization")
        
        # Initialize examples list in session state if it doesn't exist
        if 'feedback_examples' not in st.session_state:
            st.session_state.feedback_examples = [{
                "id": 0,
                "label": "FP",  # False Positive by default
                "seed": "",
                "code": "",
                "report": "",
                "description": ""
            }]
        
        # Display all examples
        st.subheader("Feedback Examples")
        examples_to_remove = []
        
        for i, example in enumerate(st.session_state.feedback_examples):
            with st.expander(f"Example {i+1}", expanded=True):
                col1, col2, col3 = st.columns([0.2, 0.7, 0.1])
                with col1:
                    label = st.radio("Example Type", 
                                   options=["FP", "FN"],
                                   key=f"label_{example['id']}",
                                   help="FP = False Positive, FN = False Negative")
                    example["label"] = label
                
                with col3:
                    if len(st.session_state.feedback_examples) > 1:
                        if st.button("Remove", key=f"remove_{example['id']}"):
                            examples_to_remove.append(example['id'])
                
                st.markdown(f"**{example['label']} Example**")
                seed = st.text_input("Seed Name",
                                    value=example.get("seed", ""),
                                    key=f"seed_{example['id']}")
                example["seed"] = seed

                code = st.text_area("Code with issue", 
                                  value=example.get("code", ""),
                                  height=150,
                                  key=f"code_{example['id']}")
                example["code"] = code
                
                report = st.text_area("Original Detection Report", 
                                    value=example.get("report", ""),
                                    height=100,
                                    key=f"report_{example['id']}",
                                    help="The incorrect detection report generated by the prompt")
                example["report"] = report
                
                description = st.text_area("Description", 
                                         value=example.get("description", ""),
                                         height=100,
                                         key=f"desc_{example['id']}",
                                         help="Explain why this is a false positive/negative")
                example["description"] = description
        
        # Remove examples marked for deletion
        if examples_to_remove:
            st.session_state.feedback_examples = [ex for ex in st.session_state.feedback_examples 
                                               if ex['id'] not in examples_to_remove]
        
        # Add new example button
        if st.button("Add Another Example"):
            # Find the highest ID and increment by 1
            max_id = max([ex["id"] for ex in st.session_state.feedback_examples]) + 1 if st.session_state.feedback_examples else 0
            st.session_state.feedback_examples.append({
                "id": max_id,
                "label": "FP",
                "seed": "",
                "code": "",
                "report": "",
                "description": ""
            })
            st.rerun()
        
        # Submit button
        if st.button("Submit Feedback", use_container_width=True):
            if not bug_type or not current_prompt:
                st.error("Please fill in all required fields (Bug Type and Current Prompt)")
            elif not any(ex["code"] for ex in st.session_state.feedback_examples):
                st.error("Please provide at least one feedback example")
            else:
                try:
                    # Validate JSON format of current prompt
                    json.loads(current_prompt)
                    
                    # Create data structure
                    examples_data = []
                    for example in st.session_state.feedback_examples:
                        if example["code"]:  # Only include examples with code
                            examples_data.append({
                                "label": example["label"],
                                "seed": example["seed"],
                                "code": example["code"],
                                "report": example["report"],
                                "description": example["description"]
                            })
                    
                    feedback_obj = {
                        "bug_type": bug_type,
                        "current_prompt": current_prompt,
                        "examples": examples_data,
                        "created_at": str(datetime.now())
                    }
                    
                    # Save the feedback
                    feedback_path = Path(f"{BASE_PATH}/src/prompt/{language}/Synthesis/feedback/{bug_type}")
                    feedback_path.mkdir(exist_ok=True, parents=True)
                    
                    # Create a unique filename
                    timestamp = time.strftime('%Y-%m-%d-%H-%M-%S', time.localtime())
                    file_path = feedback_path / f"feedback_{timestamp}.json"
                    
                    with open(file_path, "w") as f:
                        json.dump(feedback_obj, f, indent=4)
                    
                    st.success(f"Feedback saved successfully to {file_path.name}")
                    # Clear the form
                    st.session_state.feedback_examples = [{
                        "id": 0,
                        "label": "FP",
                        "seed": "",
                        "code": "",
                        "report": "",
                        "description": ""
                    }]
                except json.JSONDecodeError:
                    st.error("Current prompt is not valid JSON. Please correct it before submitting.")
    
    with tab2:
        st.subheader("Browse Existing Feedback")
        
        # Language Selection
        language = st.selectbox("Language", 
            options=["Cpp", "Python", "Java", "Go"],
            key="view_feedback_language")
        
        # Find all feedback files
        feedback_base_path = Path(f"{BASE_PATH}/src/prompt/{language}/Synthesis/feedback")
        
        if not feedback_base_path.exists():
            st.info("No feedback found. Add new feedback using the form.")
        else:
            # Find bug type directories
            bug_types = []
            for dir_path in feedback_base_path.iterdir():
                if dir_path.is_dir():
                    bug_types.append(dir_path.name)
            
            if not bug_types:
                st.info("No feedback found. Add new feedback using the form.")
            else:
                # Select bug type
                selected_bug_type = st.selectbox("Select Bug Type", 
                                              options=bug_types)
                
                # Find all feedback files for this bug type
                feedback_path = feedback_base_path / selected_bug_type
                feedback_files = list(feedback_path.glob("*.json"))
                
                if not feedback_files:
                    st.info(f"No feedback found for {selected_bug_type}. Add new feedback using the form.")
                else:
                    # Group feedback by timestamp
                    feedback_data = []
                    for file in feedback_files:
                        try:
                            with open(file, "r") as f:
                                data = json.load(f)
                                feedback_data.append((file.name, data))
                        except:
                            pass
                    
                    # Initialize session state for editing
                    if 'editing_feedback' not in st.session_state:
                        st.session_state.editing_feedback = {}
                    
                    # Display feedback
                    for name, feedback in feedback_data:
                        feedback_key = f"{name}"
                        is_editing = st.session_state.editing_feedback.get(feedback_key, False)
                        
                        with st.expander(f"Feedback: {name}", expanded=is_editing):
                            if is_editing:
                                # Edit Mode
                                st.subheader("Edit Feedback")
                                
                                # Edit current prompt
                                edited_current_prompt = st.text_area(
                                    "Current Detection Prompt", 
                                    value=feedback.get("current_prompt", ""),
                                    height=200,
                                    key=f"edit_prompt_{feedback_key}"
                                )
                                
                                # Initialize edited examples in session state if not present
                                if f"edited_feedback_{feedback_key}" not in st.session_state:
                                    st.session_state[f"edited_feedback_{feedback_key}"] = []
                                    for ex in feedback.get("examples", []):
                                        st.session_state[f"edited_feedback_{feedback_key}"].append(ex.copy())
                                
                                # Display editable examples
                                st.subheader("Edit Feedback Examples")
                                examples_to_remove = []
                                
                                for i, ex in enumerate(st.session_state[f"edited_feedback_{feedback_key}"]):
                                    with st.container():
                                        col1, col2 = st.columns([4, 1])
                                        with col1:
                                            st.markdown(f"### Example {i+1}")
                                        with col2:
                                            if len(st.session_state[f"edited_feedback_{feedback_key}"]) > 1:
                                                if st.button("Remove", key=f"remove_ex_{feedback_key}_{i}"):
                                                    examples_to_remove.append(i)
                                        
                                        # Edit example type (FP/FN)
                                        label = st.radio(
                                            "Example Type", 
                                            options=["FP", "FN"],
                                            index=0 if ex.get("label") == "FP" else 1,
                                            key=f"edit_label_{feedback_key}_{i}",
                                            horizontal=True
                                        )
                                        ex["label"] = label
                                        
                                        # Edit seed name
                                        seed = st.text_input(
                                            "Seed Name",
                                            value=ex.get("seed", ""),
                                            key=f"edit_seed_{feedback_key}_{i}"
                                        )
                                        ex["seed"] = seed

                                        # Edit code
                                        code = st.text_area(
                                            "Code",
                                            value=ex.get("code", ""),
                                            height=150,
                                            key=f"edit_code_{feedback_key}_{i}"
                                        )
                                        ex["code"] = code
                                        
                                        # Edit report
                                        report = st.text_area(
                                            "Original Detection Report",
                                            value=ex.get("report", ""),
                                            height=100,
                                            key=f"edit_report_{feedback_key}_{i}"
                                        )
                                        ex["report"] = report
                                        
                                        # Edit description
                                        description = st.text_area(
                                            "Description",
                                            value=ex.get("description", ""),
                                            height=100,
                                            key=f"edit_desc_{feedback_key}_{i}"
                                        )
                                        ex["description"] = description
                                        st.markdown("---")
                                
                                # Remove examples marked for deletion
                                if examples_to_remove:
                                    for idx in sorted(examples_to_remove, reverse=True):
                                        st.session_state[f"edited_feedback_{feedback_key}"].pop(idx)
                                    st.rerun()
                                
                                # Add new example button
                                if st.button("Add Example", key=f"add_example_{feedback_key}"):
                                    st.session_state[f"edited_feedback_{feedback_key}"].append({
                                        "label": "FP",
                                        "seed": "",
                                        "code": "",
                                        "report": "",
                                        "description": ""
                                    })
                                    st.rerun()
                                
                                # Save/Cancel buttons
                                col1, col2 = st.columns(2)
                                with col1:
                                    if st.button("Save Changes", key=f"save_{feedback_key}", use_container_width=True):
                                        try:
                                            # Validate JSON
                                            json.loads(edited_current_prompt)
                                            
                                            # Create updated data structure
                                            updated_feedback = feedback.copy()
                                            updated_feedback["current_prompt"] = edited_current_prompt
                                            updated_feedback["examples"] = st.session_state[f"edited_feedback_{feedback_key}"]
                                            updated_feedback["updated_at"] = str(datetime.now())
                                            
                                            # Save back to file
                                            file_path = feedback_path / name
                                            with open(file_path, "w") as f:
                                                json.dump(updated_feedback, f, indent=4)
                                            
                                            # Exit edit mode
                                            st.session_state.editing_feedback[feedback_key] = False
                                            st.success(f"Changes saved successfully!")
                                            # Clear session state for this feedback
                                            if f"edited_feedback_{feedback_key}" in st.session_state:
                                                del st.session_state[f"edited_feedback_{feedback_key}"]
                                            st.rerun()
                                        except json.JSONDecodeError:
                                            st.error("Current prompt is not valid JSON. Please correct it before saving.")
                                
                                with col2:
                                    if st.button("Cancel", key=f"cancel_{feedback_key}", use_container_width=True):
                                        # Exit edit mode without saving
                                        st.session_state.editing_feedback[feedback_key] = False
                                        # Clear session state for this feedback
                                        if f"edited_feedback_{feedback_key}" in st.session_state:
                                            del st.session_state[f"edited_feedback_{feedback_key}"]
                                        st.rerun()
                            
                            else:
                                # View Mode
                                st.markdown("### Current Prompt")
                                st.code(feedback.get("current_prompt", "{}"), language="json")
                                
                                st.markdown("### Examples")
                                fp_examples = [ex for ex in feedback.get("examples", []) if ex.get("label") == "FP"]
                                fn_examples = [ex for ex in feedback.get("examples", []) if ex.get("label") == "FN"]
                                
                                if fp_examples:
                                    st.markdown("#### False Positives")
                                    for i, ex in enumerate(fp_examples):
                                        st.markdown(f"**FP Example {i+1}**")
                                        st.markdown("**Seed Name:**")
                                        st.code(ex.get("seed", ""))
                                        st.markdown("**Code:**")
                                        st.code(ex.get("code", ""))
                                        st.markdown("**Original Report:**")
                                        st.text(ex.get("report", ""))
                                        if ex.get("description"):
                                            st.markdown("**Description:**")
                                            st.markdown(ex.get("description"))
                                        st.markdown("---")
                                
                                if fn_examples:
                                    st.markdown("#### False Negatives")
                                    for i, ex in enumerate(fn_examples):
                                        st.markdown(f"**FN Example {i+1}**")
                                        st.markdown("**Seed Name:**")
                                        st.code(ex.get("seed", ""))
                                        st.markdown("**Code:**")
                                        st.code(ex.get("code", ""))
                                        st.markdown("**Original Report:**")
                                        st.text(ex.get("report", ""))
                                        if ex.get("description"):
                                            st.markdown("**Description:**")
                                            st.markdown(ex.get("description"))
                                        st.markdown("---") 
                                
                                st.markdown(f"**Created:** {feedback.get('created_at', 'Unknown')}")
                                if feedback.get('updated_at'):
                                    st.markdown(f"**Last Updated:** {feedback.get('updated_at')}")
                                
                                # Add Edit and Delete buttons
                                col1, col2 = st.columns(2)
                                with col1:
                                    if st.button("Edit Feedback", key=f"edit_{feedback_key}", use_container_width=True):
                                        st.session_state.editing_feedback[feedback_key] = True
                                        st.rerun()
                                
                                with col2:
                                    if st.button("Delete Feedback", key=f"delete_{feedback_key}", use_container_width=True):
                                        try:
                                            (feedback_path / name).unlink()
                                            st.success(f"Feedback {name} deleted successfully!")
                                            st.rerun()
                                        except Exception as e:
                                            st.error(f"Failed to delete feedback: {str(e)}")
    
    with tab3:
        st.subheader("Optimize Detection Prompt")
        
        # Language Selection
        language = st.selectbox("Language", 
            options=["Cpp", "Python", "Java", "Go"],
            key="opt_language")
        
        # Model Selection
        model = st.selectbox(
            "Select Model",
            options=["claude-3.5", "claude-3.7", "o4-mini", "gpt-4o", "gpt-4-turbo", "gpt-4o-mini", "deepseek-local", "deepseek-chat", "deepseek-reasoner", "gemini"],
            help="Select the model",
            key="opt_model"
        )

        # Find all feedback directories
        feedback_base_path = Path(f"{BASE_PATH}/src/prompt/{language}/Synthesis/feedback")
        
        if not feedback_base_path.exists():
            st.info(f"No feedback found for {language}. Please add feedback first.")
        else:
            # Find bug type directories
            bug_types = []
            for dir_path in feedback_base_path.iterdir():
                if dir_path.is_dir():
                    bug_types.append(dir_path.name)
            
            if not bug_types:
                st.warning("No bug types found with feedback. Please add feedback first.")
            else:
                # Bug Type Selection
                selected_bug_type = st.selectbox(
                    "Select Bug Type",
                    options=bug_types,
                    help="Choose a bug type to optimize prompt for",
                    key="opt_bug_type"
                )
                
                # Find all feedback files for this bug type
                feedback_path = feedback_base_path / selected_bug_type
                feedback_files = list(feedback_path.glob("*.json"))
                
                if not feedback_files:
                    st.info(f"No feedback found for {selected_bug_type}. Please add feedback first.")
                else:
                    # Create a list of feedback files
                    feedback_file_info = {}
                    for file in feedback_files:
                        try:
                            with open(file, "r") as f:
                                data = json.load(f)
                                fp_count = sum(1 for ex in data.get("examples", []) if ex.get("label") == "FP")
                                fn_count = sum(1 for ex in data.get("examples", []) if ex.get("label") == "FN")
                                
                                display_name = f"{file.name} ({fp_count} FP, {fn_count} FN)"
                                feedback_file_info[display_name] = {
                                    "path": file,
                                    "data": data,
                                    "name": file.stem
                                }
                        except Exception as e:
                            pass
                    
                    # Feedback File Selection
                    selected_feedback = st.selectbox(
                        "Select Feedback",
                        options=list(feedback_file_info.keys()),
                        help="Choose feedback to use for optimizing the prompt"
                    )
                    
                    # Display feedback information
                    if selected_feedback in feedback_file_info:
                        feedback_data = feedback_file_info[selected_feedback]["data"]
                        feedback_name = feedback_file_info[selected_feedback]["name"]
                        
                        try:
                            # Show current prompt
                            st.markdown("### Current Detection Prompt")
                            st.code(feedback_data.get("current_prompt", "{}"), language="json")
                            
                            # Show example counts
                            fp_count = sum(1 for ex in feedback_data.get("examples", []) if ex.get("label") == "FP")
                            fn_count = sum(1 for ex in feedback_data.get("examples", []) if ex.get("label") == "FN")
                            st.markdown(f"**Available Feedback:** {fp_count + fn_count} examples ({fp_count} false positives, {fn_count} false negatives)")
                            
                            # Generate button
                            if st.button("Optimize Detection Prompt", type="primary", use_container_width=True):
                                with st.spinner("Optimizing prompt... This may take a moment."):
                                    try:
                                        st.session_state.optimize_prompt, elapsed_time, input_token_cost, output_token_cost = optimize_prompt(model, language, selected_bug_type, feedback_name)
                                        if st.session_state.optimize_prompt != "":
                                            st.success("Detection prompt optimized successfully!")
                                    except Exception as e:
                                        st.error(f"Failed to optimize prompt: {str(e)}")
                                        import traceback
                                        st.error(traceback.format_exc())
                            
                            if st.session_state.optimize_prompt != "":
                                # Display the optimized prompt
                                st.markdown("### Optimized Detection Prompt")
                                st.code(st.session_state.optimize_prompt, language="json")
                                
                                st.markdown("### Token Usage")
                                st.write(f"**Elapsed Time:** {elapsed_time:.2f} seconds")
                                st.write(f"**Input Token Cost:** {input_token_cost} tokens")
                                st.write(f"**Output Token Cost:** {output_token_cost} tokens")

                                # Download button
                                st.download_button(
                                    "Download Optimized Prompt",
                                    data=st.session_state.optimize_prompt,
                                    file_name=f"{selected_bug_type}_optimized_prompt.json",
                                    mime="application/json",
                                    use_container_width=True
                                )
                                
                                # Save to file option
                                if st.checkbox("Save to Prompt Library"):
                                    prompt_library_path = Path(f"{BASE_PATH}/src/prompt/{language}/Synthesis/library")
                                    prompt_library_path.mkdir(exist_ok=True, parents=True)
                                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                                    prompt_file = prompt_library_path / f"{selected_bug_type}_optimized_{timestamp}.json"
                                    
                                    st.info(f"File will be saved to: {prompt_file.absolute()}")
                                    
                                    try:
                                        with open(prompt_file, "w") as f:
                                            f.write(st.session_state.optimize_prompt)
                                        st.success(f"Prompt successfully saved to: {prompt_file.absolute()}")
                                    except Exception as e:
                                        st.error(f"Error saving file: {str(e)}")
                        except Exception as e:
                            st.error(f"Error processing feedback data: {str(e)}")

    with tab4:
        st.subheader("Evaluate Detection Prompt")

        # Language Selection
        language = st.selectbox("Language", 
            options=["Cpp", "Python", "Java", "Go"],
            key="eval_language")
        
        # Model Selection
        model = st.selectbox(
            "Select Model",
            options=["claude-3.5", "claude-3.7", "o4-mini", "gpt-4o", "gpt-4-turbo", "gpt-4o-mini", "deepseek-local", "deepseek-chat", "deepseek-reasoner", "gemini"],
            help="Select the model",
            key="eval_model"
        )

        # Find all available example files
        examples_path = Path(f"{BASE_PATH}/src/prompt/{language}/Synthesis/dataset")
        if not examples_path.exists() or not list(examples_path.glob("*.json")):
            st.info(f"No examples found for {language}. Please add examples first.")
        else:
            example_files = []
            example_file_info = {}
            
            # Get all example files
            for file in examples_path.glob("*.json"):
                try:
                    with open(file, "r") as f:
                        data = json.load(f)
                        bug_type = data.get("bug_type", "Unknown")
                        file_name = file.name
                        display_name = f"{bug_type} ({file_name})"
                        example_files.append(display_name)
                        example_file_info[display_name] = {
                            "path": file,
                            "data": data
                        }
                except Exception as e:
                    pass
            
            if not example_files:
                st.warning("No valid examples found. Please add examples with valid file formats.")
            else:
                # Example File Selection
                selected_example = st.selectbox(
                    "Select Example File",
                    options=example_files,
                    help="Choose an example file to evaluate detection prompt"
                )
                
                # Display example information
                if selected_example in example_file_info:
                    example_data = example_file_info[selected_example]["data"]
                    example_path = example_file_info[selected_example]["path"]
                    selected_bug_type = example_data.get("bug_type", "Unknown")
                    
                    try:
                        # Show pattern description
                        st.markdown("### Bug Pattern Description")
                        st.info(example_data.get("pattern_description", "No description available"))
                        
                        # Show example count
                        example_count = len(example_data.get("examples", []))
                        st.markdown(f"**Available Examples:** {example_count} ({sum(1 for ex in example_data.get('examples', []) if ex.get('label') == 'Positive')} positive, {sum(1 for ex in example_data.get('examples', []) if ex.get('label') == 'Negative')} negative)")

                        # Add prompt input section
                        st.markdown("### Enter Detection Prompt to Evaluate")
                        
                        # Provide prompt source options
                        prompt_source = st.radio(
                            "Prompt Source",
                            ["Enter Custom Prompt", "Use Optimized Prompt", "Load from File"],
                            key="eval_prompt_source"
                        )
                        
                        prompt_content = ""
                        prompt_file = None
                        
                        if prompt_source == "Enter Custom Prompt":
                            # Text area for custom prompt input
                            prompt_content = st.text_area(
                                "Enter Detection Prompt (JSON format)",
                                height=300,
                                help="Enter the detection prompt in JSON format",
                                key="eval_custom_prompt"
                            )
                            
                            # Check if prompt is valid JSON
                            if prompt_content:
                                try:
                                    json.loads(prompt_content)
                                    st.success("Valid JSON format")
                                except json.JSONDecodeError as e:
                                    st.error(f"Invalid JSON format: {str(e)}")
                                    prompt_content = None
                        
                        elif prompt_source == "Use Optimized Prompt":
                            if st.session_state.optimize_prompt == "":
                                st.warning("No optimized prompt available. Please optimize a prompt first or enter a custom prompt.")
                            else:
                                st.success("Using the optimized prompt from the Optimize tab")
                                prompt_content = st.session_state.optimize_prompt
                                st.code(prompt_content, language="json")
                        
                        else:  # Load from File
                            uploaded_file = st.file_uploader("Upload Prompt File", type=["json"])
                            if uploaded_file:
                                try:
                                    # Read the content of the uploaded file
                                    prompt_content = uploaded_file.getvalue().decode("utf-8")
                                    # Validate JSON
                                    json.loads(prompt_content)
                                    st.success("Prompt file loaded successfully")
                                    st.code(prompt_content, language="json")
                                except Exception as e:
                                    st.error(f"Error loading prompt file: {str(e)}")
                                    prompt_content = None
                        
                        # Evaluate button
                        if st.button("Evaluate", use_container_width=True):
                            if prompt_content:
                                with st.spinner("Evaluating prompt on examples..."):
                                    # First save the prompt to a temporary file
                                    temp_prompt_path = Path(f"{BASE_PATH}/tmp")
                                    temp_prompt_path.mkdir(exist_ok=True, parents=True)
                                    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                                    prompt_file = temp_prompt_path / f"{selected_bug_type}_temp_{timestamp}.json"
                                    
                                    try:
                                        # Save the prompt to the temporary file
                                        with open(prompt_file, "w") as f:
                                            f.write(prompt_content)
                                        
                                        # Get all examples from example data
                                        examples = example_data.get("examples", [])
                                        
                                        if not examples:
                                            st.warning("No examples available to evaluate.")
                                        else:
                                            # Create a table to show results
                                            results = []
                                            correct_count = 0
                                            total_count = 0
                                            
                                            # Display progress
                                            progress_bar = st.progress(0)
                                            result_container = st.container()
                                            
                                            with result_container:
                                                st.markdown("### Evaluation Results")
                                                result_table = st.empty()
                                                
                                                # Initialize the results display
                                                result_data = []
                                                
                                                # Process each example
                                                for i, example in enumerate(examples):
                                                    # Update progress
                                                    progress_bar.progress((i) / len(examples))
                                                    
                                                    seed = example.get("seed", f"Example_{i+1}")
                                                    code = example.get("code", "")
                                                    expected_label = example.get("label", "")  # Positive or Negative
                                                    
                                                    if not code:
                                                        continue
                                                        
                                                    # Expected result interpretation:
                                                    # - For Negative examples: expected_is_buggy = False (should not be detected as bug)
                                                    # - For Positive examples: expected_is_buggy = True (should be detected as bug)
                                                    expected_is_buggy = True if expected_label == "Positive" else False
                                                    
                                                    # Evaluate using the prompt
                                                    evaluation_result = evaluate_prompt(model, language, selected_bug_type, seed, code, str(prompt_file))
                                                    
                                                    if evaluation_result is None:
                                                        status = "ERROR"
                                                        explanation = "Evaluation failed"
                                                    else:
                                                        is_buggy, explanation = evaluation_result
                                                        
                                                        # Check if the result matches the expected label
                                                        if is_buggy == expected_is_buggy:
                                                            correct_count += 1
                                                            status = "CORRECT"
                                                        else:
                                                            status = "INCORRECT"
                                                    
                                                    # Add result to the data
                                                    result_data.append({
                                                        "Example": seed,
                                                        "Expected": "Is a bug" if expected_label == "Positive" else "Not a bug",
                                                        "Result": "Is a bug" if evaluation_result and evaluation_result[0] else "Not a bug",
                                                        "Status": status,
                                                        "Explanation": explanation if evaluation_result else "N/A"
                                                    })
                                                    
                                                    total_count += 1
                                                    
                                                    # Update the display
                                                    df = pd.DataFrame(result_data)
                                                    result_table.dataframe(df)
                                            
                                            # Final progress
                                            progress_bar.progress(1.0)
                                            
                                            # Display summary
                                            if total_count > 0:
                                                accuracy = (correct_count / total_count) * 100
                                                st.success(f"Evaluation complete: {correct_count}/{total_count} examples correctly classified ({accuracy:.1f}%)")
                                            else:
                                                st.warning("No examples were evaluated.")
                                    except Exception as e:
                                        st.error(f"Error during evaluation: {str(e)}")
                                        st.error(traceback.format_exc())
                            else:
                                st.error("Please provide a valid prompt to evaluate.")
                    except Exception as e:
                        st.error(f"Error processing example data: {str(e)}")

# def optimize_prompt(model, language, bug_type, feedback_file_name) -> str:
#     input = PromptOptimizerInput(language, bug_type, feedback_file_name)  # Now passing example_name directly
#     optimizer = PromptOptimizer(
#         model_name=model,
#         temperature=0,
#         language=language,
#         bug_type=bug_type,
#         max_query_num=5,
#         logger=logger
#     )
    
#     try:
#         output: PromptOptimizerOutput = optimizer.invoke(input)
#         if output and hasattr(output, 'is_valid_json') and output.is_valid_json:
#             return output.generated_prompt
#         else:
#             st.error("Generated prompt is not valid JSON.")
#             if output:
#                 return output.generated_prompt  
#             return None
#     except Exception as e:
#         st.error(f"Error during prompt synthesis: {str(e)}")
#         st.error(traceback.format_exc())
#         return None

### Measure the time and token cost of prompt optimization
def optimize_prompt(model, language, bug_type, feedback_file_name) -> Tuple[str, float, int, int]:
    start_time = time.time()
    input = PromptOptimizerInput(language, bug_type, feedback_file_name)  # Now passing example_name directly
    optimizer = PromptOptimizer(
        model_name=model,
        temperature=0,
        language=language,
        bug_type=bug_type,
        max_query_num=5,
        logger=logger
    )
    
    try:
        output: PromptOptimizerOutput = optimizer.invoke(input)
        end_time = time.time()
        elapsed_time = end_time - start_time
        if output and hasattr(output, 'is_valid_json') and output.is_valid_json:
            return output.generated_prompt, elapsed_time, optimizer.input_token_cost, optimizer.output_token_cost
        else:
            st.error("Generated prompt is not valid JSON.")
            if output:
                return output.generated_prompt, elapsed_time, optimizer.input_token_cost, optimizer.output_token_cost
            return None
    except Exception as e:
        st.error(f"Error during prompt synthesis: {str(e)}")
        st.error(traceback.format_exc())
        return None
    

def evaluate_prompt(model, language, bug_type, seed_name, function_code, prompt_file) -> Tuple[bool, str]:
    input = SliceBugDetectorInput(seed_name, function_code)
    evaluator = SliceBugDetector(
        model_name=model,
        temperature=0,
        language=language,
        bug_type=bug_type,
        max_query_num=5,
        logger=logger,
        prompt_file=prompt_file
    )
    try:
        output: SliceBugDetectorOutput = evaluator.invoke(input)
        if output is None:
            st.error("No output from intra-procedural detector.")
            return None
        return (output.is_buggy, output.explanation_str)
    
    except Exception as e:
        st.error(f"Error during evaluating prompt: {str(e)}")
        st.error(traceback.format_exc())
        return None


if __name__ == "__main__":
    st.set_page_config(
        layout="wide",  # Use wide layout instead of centered
        initial_sidebar_state="expanded"
    )
    if "optimize_prompt" not in st.session_state:
        st.session_state.optimize_prompt = ""
    optimize_page()